[package]
name = "ntk-renderer"
version.workspace = true
edition.workspace = true

[dependencies]
# member deps
ntk-common.workspace = true
ntk-core.workspace = true

# deps
egui.workspace = true
wgpu.workspace = true
egui-wgpu.workspace = true
cosmic-text.workspace = true

# helper deps
log.workspace = true
pollster.workspace = true
thiserror.workspace = true
